package cs160.final_proj_drawer.ui.itin;

import android.app.Application;

import java.lang.reflect.Array;
import java.util.ArrayList;

import androidx.annotation.NonNull;
import androidx.lifecycle.AndroidViewModel;
import androidx.lifecycle.LiveData;
import androidx.lifecycle.MutableLiveData;
import androidx.lifecycle.ViewModel;
import androidx.lifecycle.AndroidViewModel;
import cs160.final_proj_drawer.logic.FirebaseFuncs;
import cs160.final_proj_drawer.logic.ItineraryObject;
import cs160.final_proj_drawer.logic.Stop;

public class DisplayMultItinsViewModel extends AndroidViewModel {

    //holds the itins that are drawn to the view
    ArrayList<ItineraryObject> itins = new ArrayList<>();

    //all code below this comment is some boiler plate stuff i pulled
    // from the autogenerated viewModels this project came with
    private MutableLiveData<String> mText;

    public DisplayMultItinsViewModel(@NonNull Application application) {
        super(application);

        mText = new MutableLiveData<>();
        mText.setValue("This is just some junk");

        String url = FirebaseFuncs.url+"Berkeley.json";
        FirebaseFuncs.getItineraries(itins, url, getApplication().getApplicationContext());

    }


    public LiveData<String> getText() {
        return mText;
    }


    public LiveData<String> getFirebaseData() {
        return mText;
    }
/*
*/
}
